agent_defaults:
  max_tokens: 4096
  model: claude-3.5-sonnet
  temperature: 0.7
api:
  base_url: http://localhost:8000
  retries: 3
  timeout: 30
book_defaults: {}
cli:
  colors: true
  history_size: 1000
  interactive: true
core:
  debug: true
  log_level: INFO
  version: 1.0.0
database:
  max_overflow: 20
  pool_size: 10
  url: sqlite:///engine.db
logging:
  file: engine.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
monitoring:
  enabled: true
  health_check_interval: 30
  metrics_port: 9090
project_defaults: {}
protocol_defaults: {}
team_defaults: {}
tool_defaults: {}
workflow_defaults: {}
